// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdzrbldxdykrqsxqmwhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkenJibGR4ZHlrcnFzeHFtd2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzgyMTQsImV4cCI6MjA2OTc1NDIxNH0.LLz6AxP1D6Ahzx_OVm1QRRGmhJs6Cvvu6q6WT6iqDuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});